namespace Kernel.Util
{
	public enum KernelResult
	{
		NONE = -1,
		SUCCES = 0,

		FAIL = 1,
		ARGUMENT_IS_NULL = 2,
		UNSUPPORTED_TYPE = 3,
		SERIALIZATION_FAIL = 4,
		ASSERT = 5,
		REJECT_BY_RETCODE = 6,
		LUA_EXCEPTION = 7,
		IO_EXCEPTION = 8,

		BAD_CONFIG_SERIALIZER_MD5 = 101,
		BAD_LUA_CONFIG_SERIALIZER_MD5 = 102,
		FAIL_TO_DESERIALIZE_CONFIG = 103,
		FAIL_TO_GET_SERVERLIST = 104,

		NET_CONNECTION_LOST = 201,
		NET_PROTOCOL_TIMEOUT = 202,
		NET_USER_CANCEL = 203,
		NET_ANSWER_DROPPED = 204,
		NET_CONNECTION_LOST_UNMARSHAL_OR_STATE = 205,
		NET_DEVICE_OFFLINE = 206,
		NET_DATA_SERIAL_MISSMATCH = 207,
		NET_USER_LOGOUT = 208,
	}
}
